In [3]:
#导入Pandas库
import pandas as pd
#做一个小测试，定义一个变量a
a=pd.Series(range(5))
a

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [2]:
a=[1,2,3]#创建列表a
#将a转换为Series
se = pd.Series(a)
print(se)

0    1
1    2
2    3
dtype: int64

In [3]:
#创建Series
b=pd.Series([8,9,10])
b

0     8
1     9
2    10
dtype: int64

In [4]:
#创建Series
b=pd.Series([8,9,10],index=['a','b','c'])
b

a     8
b     9
c    10
dtype: int64

In [4]:
#创建二维列表
data=[['2022年1月',379,3400,320],
['2022年2月',369,2514,261],
['2022年3月',398,2856,292]]
#创建DataFrame
df=pd.DataFrame(data,columns=['日期','家居服销售量','袜子销售量','床品销售量'],index=range(1,4))
df

        日期  家居服销售量  袜子销售量  床品销售量
1  2022年1月     379   3400    320
2  2022年2月     369   2514    261
3  2022年3月     398   2856    292

In [5]:
#创建字典
data={'日期':['2022年1月','2022年2月','2022年3月'],
'家居服销售量':[397,369,398],
'袜子销售量':[3400,2514,2856],
'床品销售量':[320,261,292]}
#创建DataFrame
df=pd.DataFrame(data,index=range(1,4))
df

        日期  家居服销售量  袜子销售量  床品销售量
1  2022年1月     397   3400    320
2  2022年2月     369   2514    261
3  2022年3月     398   2856    292

In [20]:
#从DataFrame中取出一列转换为Series
a=df['家居服销售量']
#打印该列并查看数据类型
print(a)
type(a)

1    397
2    369
3    398
Name: 家居服销售量, dtype: int64

pandas.core.series.Series

In [21]:
#将Series转换为DataFrame
df1 =pd.DataFrame(a)
df1

   家居服销售量
1     397
2     369
3     398

In [22]:
type(df1)

pandas.core.frame.DataFrame

In [23]:
#计算每月所有品类销售量之和直接对列进行计算
df['总销售量']=df['家居服销售量']+df['袜子销售量']+df['床品销售量']
#查看df
df

        日期  家居服销售量  袜子销售量  床品销售量  总销售量
1  2022年1月     397   3400    320  4117
2  2022年2月     369   2514    261  3144
3  2022年3月     398   2856    292  3546

In [28]:
#①在原数据上修改列索引及行索引
df.rename(columns={"家居服销售量":"JJF","袜子销售量":"WZ","床品销售量":"CP"},index={1:"A",2:"B",3:"C"},inplace=True)
df

        日期  JJF    WZ   CP
A  2022年1月  397  3400  320
B  2022年2月  369  2514  261
C  2022年3月  398  2856  292

In [6]:
#②在原数据上修改列索引行索引
df.index=["A","B","C"]
df.columns=["日期","JJF","WZ","CP"]
df

        日期  JJF    WZ   CP
A  2022年1月  397  3400  320
B  2022年2月  369  2514  261
C  2022年3月  398  2856  292

In [7]:
#插入序号一列
df.insert(0,'序号',range(1,4))
df

   序号       日期  JJF    WZ   CP
A   1  2022年1月  397  3400  320
B   2  2022年2月  369  2514  261
C   3  2022年3月  398  2856  292

In [8]:
#删除序号一列
df.drop('序号',axis=1,inplace=True)
df

        日期  JJF    WZ   CP
A  2022年1月  397  3400  320
B  2022年2月  369  2514  261
C  2022年3月  398  2856  292

In [10]:
#查看前2行
df.head(2)

        日期  JJF    WZ   CP
A  2022年1月  397  3400  320
B  2022年2月  369  2514  261

In [11]:
#查看后2行
df.tail(2)

        日期  JJF    WZ   CP
B  2022年2月  369  2514  261
C  2022年3月  398  2856  292