## 1. 数据合并 (Merge & Concat)
- `pd.merge()`: 类似于 SQL 的 join 操作，用于根据键合并两个 DataFrame。
- `pd.concat()`: 用于沿轴（行或列）拼接多个 DataFrame。

In [1]:
#导入Pandas库
import pandas as pd
#从相对路径下获取数据表
df1=pd.read_excel('https://oss.xinchanjiao.com/upload/default/20220914-1bbc5a0e-9409-4ffa-adab-06f15090e2fb.xlsx')
#显示数据前5行
df1.head()

      年    月    门店       销售收入       销售成本       销售毛利
0  2022  Jan  门店01  478803.28  295586.23  183217.05
1  2022  Jan  门店02  442108.16  330633.55  111474.61
2  2022  Jan  门店03  367875.06  190555.04  177320.02
3  2022  Jan  门店04  174356.94  138562.72   35794.22
4  2022  Jan  门店05  182158.68  113867.90   68290.78

In [2]:
#读取Excel文件，利用converters参数强制设置“年"、“月"、"门店“三列转换为字符串类型。
df2=pd.read_excel(r'https://oss.xinchanjiao.com/upload/default/20220914-1bbc5a0e-9409-4ffa-adab-06f15090e2fb.xlsx',sheet_name='Sheet2')
#显示数据前5行
df2.head()

      年    月    门店   销售量
0  2022  Jan  门店01  1970
1  2022  Jan  门店02  2204
2  2022  Jan  门店03  1270
3  2022  Jan  门店04   923
4  2022  Jan  门店05   759

In [3]:
#Sheet1表为主，左连接数据
#未指定列，以两个DataFrame列名的交集作为连接键
df3=pd.merge(df1,df2,how='left')
df3.head()

      年    月    门店       销售收入       销售成本       销售毛利   销售量
0  2022  Jan  门店01  478803.28  295586.23  183217.05  1970
1  2022  Jan  门店02  442108.16  330633.55  111474.61  2204
2  2022  Jan  门店03  367875.06  190555.04  177320.02  1270
3  2022  Jan  门店04  174356.94  138562.72   35794.22   923
4  2022  Jan  门店05  182158.68  113867.90   68290.78   759

In [4]:
#df1,df2用concat进行纵向连接
df4=pd.concat([df1,df2],sort=False)
df4

        年    月    门店       销售收入       销售成本       销售毛利     销售量
0    2022  Jan  门店01  478803.28  295586.23  183217.05     NaN
1    2022  Jan  门店02  442108.16  330633.55  111474.61     NaN
2    2022  Jan  门店03  367875.06  190555.04  177320.02     NaN
3    2022  Jan  门店04  174356.94  138562.72   35794.22     NaN
4    2022  Jan  门店05  182158.68  113867.90   68290.78     NaN
..    ...  ...   ...        ...        ...        ...     ...
475  2022  Dec  门店36        NaN        NaN        NaN  1169.0
476  2022  Dec  门店37        NaN        NaN        NaN   815.0
477  2022  Dec  门店38        NaN        NaN        NaN   706.0
478  2022  Dec  门店39        NaN        NaN        NaN  1001.0
479  2022  Dec  门店40        NaN        NaN        NaN   669.0

[960 rows x 7 columns]

In [5]:
#df1,df2，调整axis参数用concat进行横向列连接
df4=pd.concat([df1,df2],axis=1,sort=False)
df4

        年    月    门店       销售收入       销售成本       销售毛利     年    月    门店   销售量
0    2022  Jan  门店01  478803.28  295586.23  183217.05  2022  Jan  门店01  1970
1    2022  Jan  门店02  442108.16  330633.55  111474.61  2022  Jan  门店02  2204
2    2022  Jan  门店03  367875.06  190555.04  177320.02  2022  Jan  门店03  1270
3    2022  Jan  门店04  174356.94  138562.72   35794.22  2022  Jan  门店04   923
4    2022  Jan  门店05  182158.68  113867.90   68290.78  2022  Jan  门店05   759
..    ...  ...   ...        ...        ...        ...   ...  ...   ...   ...
475  2022  Dec  门店36  260965.90  175340.61   85625.29  2022  Dec  门店36  1169
476  2022  Dec  门店37  182960.79  122197.14   60763.65  2022  Dec  门店37   815
477  2022  Dec  门店38  148970.11  105883.48   43086.63  2022  Dec  门店38   706
478  2022  Dec  门店39  268448.01  150128.45  118319.56  2022  Dec  门店39  1001
479  2022  Dec  门店40  149997.86  100382.35   49615.51  2022  Dec  门店40   669

[480 rows x 10 columns]

In [6]:
#引入库
import pandas as pd
#读取数据
df=pd.read_excel(r'https://oss.xinchanjiao.com/upload/default/20221109-780c231e-ec8d-4f7a-a878-15ca651452f7.xlsx')
#查找重复项
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
dtype: bool

## 2. 数据清洗 (Data Cleaning)
- `duplicated()`: 查找重复行。
- `drop_duplicates()`: 删除重复行。
- `dropna()`: 删除包含缺失值 (NaN) 的行或列。
- `fillna()`: 填充缺失值。

In [7]:
#删除重复项
df.drop_duplicates (inplace=True)
df.head()

      年    月    门店       销售收入         销售成本       销售毛利  门店租金
0  2022  Jan  门店01  478803.28  29  5586.23  183217.05   NaN
1  2022  Jan  门店02  442108.16    330633.55  111474.61   NaN
3  2022  Jan  门店03        NaN          NaN        NaN   NaN
4  2022  Jan  门店04  174356.94    138562.72   35794.22   NaN
6  2022  Jan  门店05        NaN          NaN        NaN   NaN

In [8]:
#删除重复项，并重置索引
df.drop_duplicates (inplace=True,ignore_index=True)
df

      年    月    门店       销售收入         销售成本       销售毛利  门店租金
0  2022  Jan  门店01  478803.28  29  5586.23  183217.05   NaN
1  2022  Jan  门店02  442108.16    330633.55  111474.61   NaN
2  2022  Jan  门店03        NaN          NaN        NaN   NaN
3  2022  Jan  门店04  174356.94    138562.72   35794.22   NaN
4  2022  Jan  门店05        NaN          NaN        NaN   NaN
5  2022  Jan  门店06  413329.60   241 064.13  172265.47   NaN
6  2022  Jan  门店07  343982.98   233 408.43  110574.55   NaN

In [9]:
#使用dropnaO在原数据上删除全为NaN的列
df.dropna(axis=1,how='all',inplace=True)
df

      年    月    门店       销售收入         销售成本       销售毛利
0  2022  Jan  门店01  478803.28  29  5586.23  183217.05
1  2022  Jan  门店02  442108.16    330633.55  111474.61
2  2022  Jan  门店03        NaN          NaN        NaN
3  2022  Jan  门店04  174356.94    138562.72   35794.22
4  2022  Jan  门店05        NaN          NaN        NaN
5  2022  Jan  门店06  413329.60   241 064.13  172265.47
6  2022  Jan  门店07  343982.98   233 408.43  110574.55

In [10]:
#以O填充所有缺失值
df.fillna(0)

      年    月    门店       销售收入         销售成本       销售毛利
0  2022  Jan  门店01  478803.28  29  5586.23  183217.05
1  2022  Jan  门店02  442108.16    330633.55  111474.61
2  2022  Jan  门店03       0.00            0       0.00
3  2022  Jan  门店04  174356.94    138562.72   35794.22
4  2022  Jan  门店05       0.00            0       0.00
5  2022  Jan  门店06  413329.60   241 064.13  172265.47
6  2022  Jan  门店07  343982.98   233 408.43  110574.55

In [11]:
#使用循环方式完成数据清洗
for i in range(df.shape[0]):
    for j in df.columns:
        df.loc[i, j] = str(df.loc[i, j]).replace(' ', '')
df

C:\Users\ItsAyaya\AppData\Local\Temp\ipykernel_9232\1567425205.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2022' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[i, j] = str(df.loc[i, j]).replace(' ', '')
C:\Users\ItsAyaya\AppData\Local\Temp\ipykernel_9232\1567425205.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '478803.28' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, j] = str(df.loc[i, j]).replace(' ', '')
C:\Users\ItsAyaya\AppData\Local\Temp\ipykernel_9232\1567425205.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '183217.05' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, j] = str(df.loc[i, j]).replace(' ', '')

      年    月    门店       销售收入       销售成本       销售毛利
0  2022  Jan  门店01  478803.28  295586.23  183217.05
1  2022  Jan  门店02  442108.16  330633.55  111474.61
2  2022  Jan  门店03        nan        nan        nan
3  2022  Jan  门店04  174356.94  138562.72   35794.22
4  2022  Jan  门店05        nan        nan        nan
5  2022  Jan  门店06   413329.6  241064.13  172265.47
6  2022  Jan  门店07  343982.98  233408.43  110574.55

## 3. 数据转换与映射 (Transformation & Mapping)
- `applymap()`: 对 DataFrame 中的每一个元素应用函数（常用于字符串处理）。
- `map()`: 对 Series 中的每一个元素应用函数或字典映射。
- `apply()`: 沿轴（行或列）应用函数。

In [12]:
#applymap函数完成数据清洗
df = df.applymap(lambda x:str(x).replace(' ',''))
df

C:\Users\ItsAyaya\AppData\Local\Temp\ipykernel_9232\3248142739.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x:str(x).replace(' ',''))

      年    月    门店       销售收入       销售成本       销售毛利
0  2022  Jan  门店01  478803.28  295586.23  183217.05
1  2022  Jan  门店02  442108.16  330633.55  111474.61
2  2022  Jan  门店03        nan        nan        nan
3  2022  Jan  门店04  174356.94  138562.72   35794.22
4  2022  Jan  门店05        nan        nan        nan
5  2022  Jan  门店06   413329.6  241064.13  172265.47
6  2022  Jan  门店07  343982.98  233408.43  110574.55

In [13]:
#将所有数字列转换为浮点数
df[['销售收入','销售成本','销售毛利']]=df[['销售收入','销售成本','销售毛利']].astype('float')
#以每列平均值填充该列缺失值，仅针对数值列
df.fillna(df.mean(numeric_only=True))

      年    月    门店        销售收入        销售成本       销售毛利
0  2022  Jan  门店01  478803.280  295586.230  183217.05
1  2022  Jan  门店02  442108.160  330633.550  111474.61
2  2022  Jan  门店03  370516.192  247851.012  122665.18
3  2022  Jan  门店04  174356.940  138562.720   35794.22
4  2022  Jan  门店05  370516.192  247851.012  122665.18
5  2022  Jan  门店06  413329.600  241064.130  172265.47
6  2022  Jan  门店07  343982.980  233408.430  110574.55

In [14]:
#读取Excel文件
data=pd.read_excel(r'https://oss.xinchanjiao.com/upload/default/20220914-1bbc5a0e-9409-4ffa-adab-06f15090e2fb.xlsx')
#显示数据前5行
data.head()

      年    月    门店       销售收入       销售成本       销售毛利
0  2022  Jan  门店01  478803.28  295586.23  183217.05
1  2022  Jan  门店02  442108.16  330633.55  111474.61
2  2022  Jan  门店03  367875.06  190555.04  177320.02
3  2022  Jan  门店04  174356.94  138562.72   35794.22
4  2022  Jan  门店05  182158.68  113867.90   68290.78

In [15]:
#方法1：使用for循环
for i in data['销售收入'].index:
    data.loc[i,'门店级别']='优秀门店' if data.loc[i,'销售收入']>=400000 else '非优秀门店'
data.head()

      年    月    门店       销售收入       销售成本       销售毛利   门店级别
0  2022  Jan  门店01  478803.28  295586.23  183217.05   优秀门店
1  2022  Jan  门店02  442108.16  330633.55  111474.61   优秀门店
2  2022  Jan  门店03  367875.06  190555.04  177320.02  非优秀门店
3  2022  Jan  门店04  174356.94  138562.72   35794.22  非优秀门店
4  2022  Jan  门店05  182158.68  113867.90   68290.78  非优秀门店

In [16]:
#使用Series.map()
data['门店级别']=data['销售收入'].map(lambda x:'优秀门店' if x>=400000 else '非优秀门店')
data.head()

      年    月    门店       销售收入       销售成本       销售毛利   门店级别
0  2022  Jan  门店01  478803.28  295586.23  183217.05   优秀门店
1  2022  Jan  门店02  442108.16  330633.55  111474.61   优秀门店
2  2022  Jan  门店03  367875.06  190555.04  177320.02  非优秀门店
3  2022  Jan  门店04  174356.94  138562.72   35794.22  非优秀门店
4  2022  Jan  门店05  182158.68  113867.90   68290.78  非优秀门店

In [17]:
#将数据中刚插入的门店级别‘列中‘优秀门店’替换成’A类门店，其他替换为‘其他门店
data['门店级别']=data['门店级别'].map({'优秀门店':'A类门店','非优秀门店':'其他门店'})
data

        年    月    门店       销售收入       销售成本       销售毛利  门店级别
0    2022  Jan  门店01  478803.28  295586.23  183217.05  A类门店
1    2022  Jan  门店02  442108.16  330633.55  111474.61  A类门店
2    2022  Jan  门店03  367875.06  190555.04  177320.02  其他门店
3    2022  Jan  门店04  174356.94  138562.72   35794.22  其他门店
4    2022  Jan  门店05  182158.68  113867.90   68290.78  其他门店
..    ...  ...   ...        ...        ...        ...   ...
475  2022  Dec  门店36  260965.90  175340.61   85625.29  其他门店
476  2022  Dec  门店37  182960.79  122197.14   60763.65  其他门店
477  2022  Dec  门店38  148970.11  105883.48   43086.63  其他门店
478  2022  Dec  门店39  268448.01  150128.45  118319.56  其他门店
479  2022  Dec  门店40  149997.86  100382.35   49615.51  其他门店

[480 rows x 7 columns]

In [18]:
#沿着0轴计算，销售收入、销售成本、销售毛利沿着数据列分别进行除以10000，保留四位小数
data[['销售收入','销售成本','销售毛利']]=data[['销售收入','销售成本','销售毛利']].apply(lambda x:round(x/10000,4),axis=0)
#修改列名
data.rename(columns={'销售收入':'销售收入(万元)','销售成本':'销售成本(万元)','销售毛利':'销售毛利(万元)'},inplace=True)
data.head()

      年    月    门店  销售收入(万元)  销售成本(万元)  销售毛利(万元)  门店级别
0  2022  Jan  门店01   47.8803   29.5586   18.3217  A类门店
1  2022  Jan  门店02   44.2108   33.0634   11.1475  A类门店
2  2022  Jan  门店03   36.7875   19.0555   17.7320  其他门店
3  2022  Jan  门店04   17.4357   13.8563    3.5794  其他门店
4  2022  Jan  门店05   18.2159   11.3868    6.8291  其他门店

In [19]:
#按行(axis=1)的实现计算毛利率，计算结果后添加”%”，并存储在【销售毛利率】列
def func_01(row):
    row['销售毛利率']=format(row['销售毛利']/row['销售收入'],'2%')#format()格式化函数
    return row
data[['销售收入','销售成本','销售毛利']].apply(func_01,axis=1)

KeyError: "None of [Index(['销售收入', '销售成本', '销售毛利'], dtype='object')] are in the [columns]"

In [ ]:
#将DataFrame中销售收入，销售成本和销售毛利统一保留一位小数显示
data[['销售收入','销售成本','销售毛利']].applymap(lambda x:"%.1f"%x)

C:\Users\ItsAyaya\AppData\Local\Temp\ipykernel_29712\1596086071.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data[['销售收入','销售成本','销售毛利']].applymap(lambda x:"%.1f"%x)

         销售收入      销售成本      销售毛利
0    478803.3  295586.2  183217.0
1    442108.2  330633.5  111474.6
2    367875.1  190555.0  177320.0
3    174356.9  138562.7   35794.2
4    182158.7  113867.9   68290.8
..        ...       ...       ...
475  260965.9  175340.6   85625.3
476  182960.8  122197.1   60763.7
477  148970.1  105883.5   43086.6
478  268448.0  150128.5  118319.6
479  149997.9  100382.4   49615.5

[480 rows x 3 columns]

In [ ]:
#Group By

## 4. 数据分组与聚合 (GroupBy & Aggregation)
- `groupby()`: 根据一个或多个键对数据进行分组。
- `sum()`, `mean()`: 对分组后的数据进行聚合计算。
- `agg()`: 同时应用多个聚合函数。

In [ ]:
#导入Pandas库
import pandas as pd
#读取Excel文件
data=pd.read_excel(r'https://oss.xinchanjiao.com/upload/default/20220914-1bbc5a0e-9409-4ffa-adab-06f15090e2fb.xlsx')
#显示数据前5行
data.head()

      年    月    门店       销售收入       销售成本       销售毛利
0  2022  Jan  门店01  478803.28  295586.23  183217.05
1  2022  Jan  门店02  442108.16  330633.55  111474.61
2  2022  Jan  门店03  367875.06  190555.04  177320.02
3  2022  Jan  门店04  174356.94  138562.72   35794.22
4  2022  Jan  门店05  182158.68  113867.90   68290.78

In [ ]:
#创建一个英文月份和数字月份对照的字典，将英文月份转换为数字字符串
monthdict={'Jan':'01','Feb':'02','Mar':'03','Apr':'04','May':'05','Jun':'06',
'Jul':'07','Aug':'08','Sep':'09','Oct':'10','Nov':'11','Dec':'12'}
data['月']=data['月'].map(monthdict)
data

        年   月    门店       销售收入       销售成本       销售毛利
0    2022  01  门店01  478803.28  295586.23  183217.05
1    2022  01  门店02  442108.16  330633.55  111474.61
2    2022  01  门店03  367875.06  190555.04  177320.02
3    2022  01  门店04  174356.94  138562.72   35794.22
4    2022  01  门店05  182158.68  113867.90   68290.78
..    ...  ..   ...        ...        ...        ...
475  2022  12  门店36  260965.90  175340.61   85625.29
476  2022  12  门店37  182960.79  122197.14   60763.65
477  2022  12  门店38  148970.11  105883.48   43086.63
478  2022  12  门店39  268448.01  150128.45  118319.56
479  2022  12  门店40  149997.86  100382.35   49615.51

[480 rows x 6 columns]

In [ ]:
#根据月列进行分组，求各月总和
data.groupby('月').sum()

,年,门店,销售收入,销售成本,销售毛利
月,,,,,
01,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11985859.71,7703724.63,4282135.08
02,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11861774.91,7623243.43,4238531.48
03,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11737690.11,7542762.23,4194927.88
04,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12073592.11,7728569.03,4345023.08
05,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11949507.31,7648087.83,4301419.48
06,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11825422.51,7567606.63,4257815.88
07,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12161324.51,7753413.43,4407911.08
08,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12037239.71,7672932.23,4364307.48
09,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11913154.91,7592451.03,4320703.88
10,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12249056.91,7778257.83,4470799.08
11,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12124972.11,7697776.63,4427195.48
12,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12000887.31,7617295.43,4383591.88

In [ ]:
#将根据年、月列聚合，计算销售收入总和，销售成本平均值
data.groupby(['年','月']).agg({'销售收入':'sum','销售成本':'mean'})

                销售收入          销售成本
年    月
2022 01  11985859.71  192593.11575
     02  11861774.91  190581.08575
     03  11737690.11  188569.05575
     04  12073592.11  193214.22575
     05  11949507.31  191202.19575
     06  11825422.51  189190.16575
     07  12161324.51  193835.33575
     08  12037239.71  191823.30575
     09  11913154.91  189811.27575
     10  12249056.91  194456.44575
     11  12124972.11  192444.41575
     12  12000887.31  190432.38575

In [24]:
#导入Pandas库
import pandas as pd
#读取Excel文件
data=pd.read_excel(r'https://oss.xinchanjiao.com/upload/default/20220914-1bbc5a0e-9409-4ffa-adab-06f15090e2fb.xlsx')
#显示数据前5行
data.head()

      年    月    门店       销售收入       销售成本       销售毛利
0  2022  Jan  门店01  478803.28  295586.23  183217.05
1  2022  Jan  门店02  442108.16  330633.55  111474.61
2  2022  Jan  门店03  367875.06  190555.04  177320.02
3  2022  Jan  门店04  174356.94  138562.72   35794.22
4  2022  Jan  门店05  182158.68  113867.90   68290.78

In [25]:
#创建一个英文月份和数字月份对照的字典，将英文月份转换为数字字符串
monthdict={'Jan':'01','Feb':'02','Mar':'03','Apr':'04','May':'05','Jun':'06','Jul':'07','Aug':'08','Sep':'09','Oct':'10','Nov':'11','Dec':'12',}
data['月']= data['月'].map(monthdict)
data

        年   月    门店       销售收入       销售成本       销售毛利
0    2022  01  门店01  478803.28  295586.23  183217.05
1    2022  01  门店02  442108.16  330633.55  111474.61
2    2022  01  门店03  367875.06  190555.04  177320.02
3    2022  01  门店04  174356.94  138562.72   35794.22
4    2022  01  门店05  182158.68  113867.90   68290.78
..    ...  ..   ...        ...        ...        ...
475  2022  12  门店36  260965.90  175340.61   85625.29
476  2022  12  门店37  182960.79  122197.14   60763.65
477  2022  12  门店38  148970.11  105883.48   43086.63
478  2022  12  门店39  268448.01  150128.45  118319.56
479  2022  12  门店40  149997.86  100382.35   49615.51

[480 rows x 6 columns]

In [26]:
#行为月’，列为‘年，统计指标为销售收入的合计和销售毛利的平均数，在透视表中加上汇总栏
df1 =pd.pivot_table(data,
            index=['月'],
            columns=['年'],
            values=['销售收入','销售毛利'],
            aggfunc={'销售收入':'sum','销售毛利':'mean'},
            fill_value=0,
            margins=True,
            margins_name='汇总')
df1

            销售收入                      销售毛利
年           2022            汇总        2022          汇总
月
01  1.198586e+07  1.198586e+07  107053.377  107053.377
02  1.186177e+07  1.186177e+07  105963.287  105963.287
03  1.173769e+07  1.173769e+07  104873.197  104873.197
04  1.207359e+07  1.207359e+07  108625.577  108625.577
05  1.194951e+07  1.194951e+07  107535.487  107535.487
06  1.182542e+07  1.182542e+07  106445.397  106445.397
07  1.216132e+07  1.216132e+07  110197.777  110197.777
08  1.203724e+07  1.203724e+07  109107.687  109107.687
09  1.191315e+07  1.191315e+07  108017.597  108017.597
10  1.224906e+07  1.224906e+07  111769.977  111769.977
11  1.212497e+07  1.212497e+07  110679.887  110679.887
12  1.200089e+07  1.200089e+07  109589.797  109589.797
汇总  1.439205e+08  1.439205e+08  108321.587  108321.587

## 5. 透视表与重塑 (Pivot Table & Reshaping)
- `pivot_table()`: 创建电子表格风格的透视表。
- `stack()`: 将列索引旋转为行索引（列转行）。
- `unstack()`: 将行索引旋转为列索引（行转列）。

In [27]:
#根据月列进行分组，求各月总和
data1= data.groupby('月').sum()
data1

,年,门店,销售收入,销售成本,销售毛利
月,,,,,
01,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11985859.71,7703724.63,4282135.08
02,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11861774.91,7623243.43,4238531.48
03,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11737690.11,7542762.23,4194927.88
04,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12073592.11,7728569.03,4345023.08
05,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11949507.31,7648087.83,4301419.48
06,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11825422.51,7567606.63,4257815.88
07,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12161324.51,7753413.43,4407911.08
08,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12037239.71,7672932.23,4364307.48
09,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,11913154.91,7592451.03,4320703.88
10,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12249056.91,7778257.83,4470799.08
11,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12124972.11,7697776.63,4427195.48
12,80880,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,12000887.31,7617295.43,4383591.88

In [28]:
#使用stack函数，将销售收入、销售成本、销售毛利索引转换到行索引
data1.stack(level=-1)

月
01  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          11985859.71
    销售成本                                           7703724.63
    销售毛利                                           4282135.08
02  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          11861774.91
    销售成本                                           7623243.43
    销售毛利                                           4238531.48
03  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          11737690.11
    销售成本                                           7542762.23
    销售毛利                                           4194927.88
04  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          12073592.11
    销售成本                                           7728569.03
    销售毛利                                           4345023.08
05  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          11949507.31
    销售成本                                           7648087.83
    销售毛利                                           4301419.48
06  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          11825422.51
    销售成本                                           7567606.63
    销售毛利                                           4257815.88
07  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          12161324.51
    销售成本                                           7753413.43
    销售毛利                                           4407911.08
08  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          12037239.71
    销售成本                                           7672932.23
    销售毛利                                           4364307.48
09  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          11913154.91
    销售成本                                           7592451.03
    销售毛利                                           4320703.88
10  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          12249056.91
    销售成本                                           7778257.83
    销售毛利                                           4470799.08
11  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          12124972.11
    销售成本                                           7697776.63
    销售毛利                                           4427195.48
12  年                                                   80880
    门店      门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
    销售收入                                          12000887.31
    销售成本                                           7617295.43
    销售毛利                                           4383591.88
dtype: object

In [30]:
#使用stack函数，将销售收入、销售成本、销售毛利索引转换到行索引
data1.stack().unstack(0)

月,01,02,03,04,05,06,07,08,09,10,11,12
年,80880,80880,80880,80880,80880,80880,80880,80880,80880,80880,80880,80880
门店,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...,门店01门店02门店03门店04门店05门店06门店07门店08门店09门店10门店11门店...
销售收入,11985859.71,11861774.91,11737690.11,12073592.11,11949507.31,11825422.51,12161324.51,12037239.71,11913154.91,12249056.91,12124972.11,12000887.31
销售成本,7703724.63,7623243.43,7542762.23,7728569.03,7648087.83,7567606.63,7753413.43,7672932.23,7592451.03,7778257.83,7697776.63,7617295.43
销售毛利,4282135.08,4238531.48,4194927.88,4345023.08,4301419.48,4257815.88,4407911.08,4364307.48,4320703.88,4470799.08,4427195.48,4383591.88